version: "3"
services:
  app:
    build: .
    depends_on:
      - flat-db
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      NODE_ENV: ${NODE_ENV}
      PORT: ${APP_PORT}
    ports:
      - "3000:3000"
    volumes:
      - .:/app/
      - /app/node_modules

  flat-db:
    image: postgres:11
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
