version: '3'

services:
    db:
      container_name: flats_postgres
      image: postgres:10
      env_file:
        - .env
      volumes:
        - /pgdata:/var/lib/postgresql/data

    flats-app:
      build:
        context: "."
        dockerfile: "./Dockerfile"
      container_name: flat_app
      command: npm run dev
      depends_on:
        - db
      env_file:
        - .env
      environment:
        DATABASE_URL: postgres://${DATABASE_USER}:${DATABASE_PASSWORD}@db:5432/${DATABASE}
        NODE_ENV: ${NODE_ENV}
        PORT: ${PORT}
      ports:
        - ${PORT}:${PORT}
      volumes:
        - .:/app/
        - /app/node_modules
